export const AUDIO_CONFIG = {
  // UI & General
  'ui_click': 'Assets/Sound Effects/Skills/dash1.mp3',
  'ui_hover': 'Assets/Sound Effects/Skills/dash3.mp3',
  'ui_bell': 'Assets/Sound Effects/Announcer/bell.mp3',
  'bell': 'Assets/Sound Effects/Announcer/bell.mp3',
  'timertick': 'Assets/Sound Effects/Announcer/timertick.mp3',
  'fight': 'Assets/Sound Effects/Announcer/fight.mp3',
  'ringbell': 'Assets/Sound Effects/Announcer/ring-bell.mp3',
  'ring_bell': 'Assets/Sound Effects/Announcer/ring-bell.mp3',
  'youwin': 'Assets/Sound Effects/Announcer/street-fighter-ii-you-win.mp3',
  'street_fighter_you_win': 'Assets/Sound Effects/Announcer/street-fighter-ii-you-win.mp3',

  // Attacks
  'attack_explosion': 'Assets/Sound Effects/Attacks/explosion.mp3',
  'attack_fireball': 'Assets/Sound Effects/Skills/fugatravel.mp3',
  'attack_fleshhit': 'Assets/Sound Effects/Attacks/fleshhit.mp3',
  'attack_groundsmash': 'Assets/Sound Effects/Attacks/groundSmash.mp3',
  'attack_swordswing': 'Assets/Sound Effects/Attacks/swordswing.mp3',
  'attack_escanor': 'Assets/Sound Effects/Attacks/Escanor-attack.mp3',
  'attack_sukunaslice': 'Assets/Sound Effects/Attacks/Sukuna-slice.mp3',
  'sukuna_slice': 'Assets/Sound Effects/Attacks/Sukuna-slice.mp3',
  
  // Effects
  'effect_flare': 'Assets/Sound Effects/SkillEffects/flare.mp3',
  'effect_infinity_collide': 'Assets/Sound Effects/SkillEffects/infinity-collide.mp3',
  'effect_escanor_weapon_lift': 'Assets/Sound Effects/SkillEffects/Escanor-weapon-lift.mp3',
  'walk_on_grass': 'Assets/Sound Effects/Sprites SFX/walk-on-grass.mp3',
  'bush_rustle': 'Assets/Sound Effects/Sprites SFX/walk-on-grass.mp3',
  'yuta_boss_entrance_voiceline': 'Assets/Sound Effects/Boss Voiceline SFX/yuta-boss-entrance-voiceline.mp3',
  'crazydave_sun_pickup': 'Assets/Sound Effects/Sprites SFX/crazydave-sun-pickup.mp3',
  'crazydave_peashooter_shot': 'Assets/Sound Effects/Attacks/crazydave-peashooter-shot.mp3',
  'crazydave_pea_splat': 'Assets/Sound Effects/SkillEffects/splat3.ogg',
  'splat3': 'Assets/Sound Effects/SkillEffects/splat3.ogg',
  'crazydave_planting': 'Assets/Sound Effects/SkillEffects/crazydave-Planting.ogg',

  // Skills
  'skill_backstab': 'Assets/Sound Effects/Skills/backstab.mp3',
  'skill_comerika': 'Assets/Sound Effects/Skills/comerika.mp3',
  'skill_dash1': 'Assets/Sound Effects/Skills/dash1.mp3',
  'skill_dash3': 'Assets/Sound Effects/Skills/dash3.mp3',
  'skill_dash5': 'Assets/Sound Effects/Skills/dash5.mp3',
  'skill_domainexpansion': 'Assets/Sound Effects/Skills/domainexpansion.mp3',
  'skill_enhance': 'Assets/Sound Effects/Skills/enhance.mp3',
  'skill_fuga': 'Assets/Sound Effects/Skills/fuga.mp3',
  'skill_fuga_explode': 'Assets/Sound Effects/Skills/fugaexplode.mp3',
  'fuga_explode': 'Assets/Sound Effects/Skills/fugaexplode.mp3',
  'skill_gojodomain': 'Assets/Sound Effects/Skills/gojodomain.mp3',
  'skill_machinebroken': 'Assets/Sound Effects/Skills/machinebroken.mp3',
  'skill_mixing': 'Assets/Sound Effects/Skills/mixing.mp3',
  'skill_parry': 'Assets/Sound Effects/Skills/parry.mp3',
  'skill_redchanneling': 'Assets/Sound Effects/Skills/redchanneling.mp3',
  'skill_redcharging': 'Assets/Sound Effects/Skills/redcharging.mp3',
  'skill_reddeploy': 'Assets/Sound Effects/Skills/reddeploy.mp3',
  'skill_redblast': 'Assets/Sound Effects/Skills/redblast.mp3',
  'redchanneling': 'Assets/Sound Effects/Skills/redchanneling.mp3',
  'redcharging': 'Assets/Sound Effects/Skills/redcharging.mp3',
  'reddeploy': 'Assets/Sound Effects/Skills/reddeploy.mp3',
  'redblast': 'Assets/Sound Effects/Skills/redblast.mp3',
  'skill_rikaAppearance1': 'Assets/Sound Effects/Skills/rikaAppearance1.mp3',
  'skill_shieldcharge': 'Assets/Sound Effects/Skills/shieldcharge.mp3',
  'skill_spinslash': 'Assets/Sound Effects/Skills/spinslash.mp3',
  'skill_thunderstrike': 'Assets/Sound Effects/Skills/thunderstrike.mp3',
  'skill_todoclap': 'Assets/Sound Effects/Skills/todo-clap.mp3',
  'skill_genosinceneratevoice': 'Assets/Sound Effects/Skills/genos-incenerate-voice.mp3',
  'skill_genosinceneratecharging': 'Assets/Sound Effects/Skills/genos-incenerate-charging.mp3',
  'skill_genosincenerateblast': 'Assets/Sound Effects/Skills/genos-incenerate-blast.mp3',
  'skill_genosultimatecharging': 'Assets/Sound Effects/Skills/genos-ultimatecharging.mp3',
  'skill_genosultimateblast': 'Assets/Sound Effects/Skills/genos-ultimateblast.mp3',
  'skill_genosmachinegunblowvoice': 'Assets/Sound Effects/Skills/genos-machinegunblow-voice.mp3',
  'skill_genosrecovery': 'Assets/Sound Effects/Skills/genos-recovery.mp3',
  'skill_genosrangeattack': 'Assets/Sound Effects/Attacks/genos-range-attack.mp3',
  'skill_genosdashnoise': 'Assets/Sound Effects/Skills/genos-dash-noise.mp3',
  'skill_genosselfdestructcharging': 'Assets/Sound Effects/Skills/genos-selfdestruct-charging.mp3',
  'skill_genosselfdestructexplosion': 'Assets/Sound Effects/Skills/genos-selfdestruct-explosion.mp3',
  'skill_todotadakachannelvoice': 'Assets/Sound Effects/Skills/todo-tadakaimagination-voiceline.mp3',
  'skill_todotadakabgsong': 'Assets/Sound Effects/Skills/todo-tadaka-background-song.mp3',
  'skill_todomybestfriend': 'Assets/Sound Effects/SkillEffects/todo-voiceline-mybestfriend.mp3',
  'skill_yujibestfriend': 'Assets/Sound Effects/SkillEffects/yuji-voiceline-bestfriend.mp3',
  'skill_saitamachampion': 'Assets/Sound Effects/SkillEffects/saitama-champion-voiceline.mp3',
  'skill_johnwick_shell_drop': 'Assets/Sound Effects/Skills/johnwick-bulleshell-drop.mp3',
  'skill_johnwick_gun_drop': 'Assets/Sound Effects/Skills/johnwick-gundrop.mp3',
  'skill_johnwick_gun_switch': 'Assets/Sound Effects/Skills/johnwick-gunswitch.mp3',
  'skill_johnwick_m4_reload': 'Assets/Sound Effects/Skills/johnwick-m4-reload.mp3',
  'skill_johnwick_m4_shot': 'Assets/Sound Effects/Skills/johnwick-m4-shot.mp3',
  'skill_johnwick_pencil_stab': 'Assets/Sound Effects/Skills/johnwick-pencilstab.mp3',
  'skill_johnwick_pistol_reload': 'Assets/Sound Effects/Skills/johnwick-pistol-reload.mp3',
  'skill_johnwick_pistol_shot': 'Assets/Sound Effects/Skills/johnwick-pistol-shot.mp3',
  'skill_johnwick_shotgun_crack': 'Assets/Sound Effects/Skills/johnwick-shotgun-crack.mp3',
  'skill_johnwick_shotgun_reload': 'Assets/Sound Effects/Skills/johnwick-shotgun-reload.mp3',
  'skill_johnwick_switchgun_voice': 'Assets/Sound Effects/Skills/johnwick-switchgun-voiceline.mp3',
  'skill_johnwick_rollback_voice': 'Assets/Sound Effects/Skills/Johnwick-rollback-voiceline.mp3',
  'skill_engineer_sentry_destroyed': 'Assets/Sound Effects/Skills/engineer-sentrydestroyed.mp3',
  'skill_engineer_sentry_detected': 'Assets/Sound Effects/Skills/engineer-sentrydetected.mp3',
  'skill_engineer_sentry_gunshot': 'Assets/Sound Effects/Skills/engineer-sentrygunshot.mp3',
  'skill_engineer_sentry_reloaded': 'Assets/Sound Effects/Skills/engineer-sentryreloaded.mp3',
  'skill_engineer_sentry_reloading': 'Assets/Sound Effects/Skills/engineer-sentryreloading.mp3',
  'skill_engineer_repair': 'Assets/Sound Effects/Skills/repair.mp3',
  'repair': 'Assets/Sound Effects/Skills/repair.mp3',

  // CJ Grove Street
  'skill_cj_carroam_noise': 'Assets/Sound Effects/Skills/cj-carroam-noise.mp3',
  'skill_cj_cheatactivated_banner': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'skill_cj_cheatactivated': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'cheatActivated': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'cheat_activated': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'cj_cheatactivated_banner': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'skill_cj_deathmusic': 'Assets/Sound Effects/Skills/cj-deathmusic.mp3',
  'skill_cj_grovestreet_voiceline': 'Assets/Sound Effects/Skills/cj-GROVESTREET4LIFE-voiceline.mp3',
  'skill_cj_homiesarrival_voiceline': 'Assets/Sound Effects/Skills/cj-homiesarrival-voiceline.mp3',
  'skill_cj_homiearrival_voiceline2': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline2.mp3',
  'skill_cj_homiearrival_voiceline3': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline3.mp3',
  'skill_cj_homiearrival_voiceline4': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline4.mp3',
  'skill_cj_homies_noise1': 'Assets/Sound Effects/Skills/cj-homies-noise1.mp3',
  'skill_cj_homies_noise2': 'Assets/Sound Effects/Skills/cj-homies-noise2.mp3',
  'skill_cj_homie_noise3': 'Assets/Sound Effects/Skills/cj-homie-noise3.mp3',
  'skill_cj_homie_noise4': 'Assets/Sound Effects/Skills/cj-homie-noise4.mp3',
  'skill_cj_homie_noise5': 'Assets/Sound Effects/Skills/cj-homie-noise5.mp3',
  'skill_cj_intro_voiceline': 'Assets/Sound Effects/Skills/cj-intro-voiceline.mp3',
  'skill_cj_respectoverlay_bgmusic': 'Assets/Sound Effects/Skills/cj-respectoverlay-bgmusic.mp3',
  'skill_cj_typeclick1letter_noise': 'Assets/Sound Effects/Skills/cj-typeclick1letter-noise.mp3',
  'typeClickNoise': 'Assets/Sound Effects/Skills/cj-typeclick1letter-noise.mp3',

  // Reze (Bomb Devil)
  'skill_reze_pin_pull': 'Assets/Sound Effects/Skills/parry.mp3',
  'skill_reze_spark_burst': 'Assets/Sound Effects/Attacks/flamespray1.mp3',
  'skill_reze_explosion_small': 'Assets/Sound Effects/Attacks/explosion.mp3',
  'skill_reze_explosion_large': 'Assets/Sound Effects/Skills/fugaexplode.mp3',
  'skill_reze_rocket_jet': 'Assets/Sound Effects/Skills/genos-dash-noise.mp3',
  'skill_reze_nuke_charge': 'Assets/Sound Effects/Skills/genos-ultimatecharging.mp3',
  'skill_reze_nuke_dive': 'Assets/Sound Effects/Skills/fugatravel.mp3',
  'skill_reze_nuke_impact': 'Assets/Sound Effects/Skills/genos-selfdestruct-explosion.mp3',

  // Zenitsu (Thunder Breathing)
  'skill_zenitsu_dash_noise': 'Assets/Sound Effects/Skills/Zenitsu-dash-noise.mp3',
  'skill_zenitsu_dash2': 'Assets/Sound Effects/Skills/Zenitsu-dash2.mp3',
  'skill_zenitsu_firstform_voiceline': 'Assets/Sound Effects/Skills/Zenitsu-firstform-voiceline.mp3',
  'skill_zenitsu_sixfold_voiceline': 'Assets/Sound Effects/Skills/zenitsu-sixfold-voiceline.mp3',
  'skill_zenitsu_thunderclap_flash_voiceline': 'Assets/Sound Effects/Skills/Zenitsu-thunderclap&flash-voiceline.mp3',
  'zenitsu_firstform_voiceline': 'Assets/Sound Effects/Skills/Zenitsu-firstform-voiceline.mp3',
  'zenitsu_sixfold_voiceline': 'Assets/Sound Effects/Skills/zenitsu-sixfold-voiceline.mp3',
  'zenitsu_thunderclap_flash_voiceline': 'Assets/Sound Effects/Skills/Zenitsu-thunderclap&flash-voiceline.mp3',
  'Zenitsu-firstform-voiceline': 'Assets/Sound Effects/Skills/Zenitsu-firstform-voiceline.mp3',
  'zenitsu-sixfold-voiceline': 'Assets/Sound Effects/Skills/zenitsu-sixfold-voiceline.mp3',
  'Zenitsu-thunderclap&flash-voiceline': 'Assets/Sound Effects/Skills/Zenitsu-thunderclap&flash-voiceline.mp3',
  'skill_zenitsu_electric1': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise1.mp3',
  'skill_zenitsu_electric2': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise2.mp3',
  'skill_zenitsu_electric3': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise3.mp3',
  'zenitsu_dash_noise': 'Assets/Sound Effects/Skills/Zenitsu-dash-noise.mp3',
  'zenitsu_dash2': 'Assets/Sound Effects/Skills/Zenitsu-dash2.mp3',
  'zenitsu_electric1': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise1.mp3',
  'zenitsu_electric2': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise2.mp3',
  'zenitsu_electric3': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise3.mp3',
  'zenitsu_electric_noise1': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise1.mp3',
  'zenitsu_electric_noise2': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise2.mp3',
  'zenitsu_electric_noise3': 'Assets/Sound Effects/Skills/Zenitsu-electric-noise3.mp3',

  // Crazy Dave (Plants vs Zombies)
  'crazydave_peashooter_shot': 'Assets/Sound Effects/Attacks/crazydave-peashooter-shot.mp3',
  'crazydave_snowpea_shot': 'Assets/Sound Effects/Attacks/crazydave-snow_pea_sparkles.ogg',
  'crazydave_snowpea_freeze': 'Assets/Sound Effects/SkillEffects/crazydave-snowpea-freeze.mp3',
  'crazydave_splat': 'Assets/Sound Effects/SkillEffects/splat3.ogg',
  'crazydave_lawnmower_engine': 'Assets/Sound Effects/Sprites SFX/Lawn Mower.mp3',
  'lawnmower_engine': 'Assets/Sound Effects/Sprites SFX/Lawn Mower.mp3',

  // Nameless Deity (Terraria: Wrath of the Gods)
  'nameless_laser_charge': 'Assets/Sound Effects/NamelessDeity/CosmicLaserChargeUp.ogg',
  'nameless_laser_start': 'Assets/Sound Effects/NamelessDeity/CosmicLaserStart.ogg',
  'nameless_laser_loop': 'Assets/Sound Effects/NamelessDeity/CosmicLaserLoop.ogg',
  'nameless_laser_hit': 'Assets/Sound Effects/NamelessDeity/CosmicLaserObliteration.ogg',
  'nameless_chant1': 'Assets/Sound Effects/NamelessDeity/ChantLoop1.ogg',
  'nameless_chant2': 'Assets/Sound Effects/NamelessDeity/ChantLoop2.ogg',
  'nameless_mumble1': 'Assets/Sound Effects/NamelessDeity/Mumble1.ogg',
  'nameless_mumble2': 'Assets/Sound Effects/NamelessDeity/Mumble2.ogg',
  'nameless_mumble3': 'Assets/Sound Effects/NamelessDeity/Mumble3.ogg',
  'nameless_mumble4': 'Assets/Sound Effects/NamelessDeity/Mumble4.ogg',
  'nameless_mumble5': 'Assets/Sound Effects/NamelessDeity/Mumble5.ogg',
  'nameless_dart_shoot': 'Assets/Sound Effects/NamelessDeity/SunBeamShoot.ogg',
  'nameless_portal_laser': 'Assets/Sound Effects/NamelessDeity/PortalLaserShoot.ogg',
  'nameless_dimension_cleave': 'Assets/Sound Effects/NamelessDeity/RealityTear.ogg',
  'nameless_slice_telegraph': 'Assets/Sound Effects/NamelessDeity/SliceTelegraph.ogg',
  'nameless_star_convergence': 'Assets/Sound Effects/NamelessDeity/StarConvergence.ogg',
  'nameless_star_convergence_fast': 'Assets/Sound Effects/NamelessDeity/StarConvergenceFast.ogg',
  'nameless_supernova': 'Assets/Sound Effects/NamelessDeity/Supernova.ogg',
  'nameless_big_supernova': 'Assets/Sound Effects/NamelessDeity/BigSupernova.ogg',
  'nameless_moment_of_creation': 'Assets/Sound Effects/NamelessDeity/MomentOfCreation.ogg',
  'nameless_chuckle': 'Assets/Sound Effects/NamelessDeity/Chuckle.ogg',
  'nameless_wing_flap': 'Assets/Sound Effects/NamelessDeity/WingFlap2.ogg',

  // Avatar of Emptiness (Terraria: Wrath of the Gods)
  'avatar_rift_shoot': 'Assets/Sound Effects/Avatar/RiftShoot1.ogg',
  'avatar_frost_column_burst': 'Assets/Sound Effects/Avatar/FrostColumnBurst.ogg',
  'avatar_frost_column_charge': 'Assets/Sound Effects/Avatar/FrostColumnChargeUp.ogg',
  'avatar_reality_impact': 'Assets/Sound Effects/Avatar/RealityImpact.ogg',
  'avatar_portal_hand_reach': 'Assets/Sound Effects/Avatar/PortalHandReach1.ogg',
  'avatar_portal_pierce': 'Assets/Sound Effects/Avatar/PortalPierce1.ogg',
  'avatar_annihilation_charge': 'Assets/Sound Effects/Avatar/UniversalAnnihilationCharge.ogg',
  'avatar_annihilation_blast': 'Assets/Sound Effects/Avatar/UniversalAnnihilationBlast.ogg',
  'avatar_annihilation_loop': 'Assets/Sound Effects/Avatar/UniversalAnnihilationLoop.ogg',
  'avatar_reality_shatter': 'Assets/Sound Effects/Avatar/RealityShatter1.ogg',
  'avatar_hurt': 'Assets/Sound Effects/Avatar/AvatarHurt1.ogg'
};

/**
 * 90s Arcade Retro Voiceline DSP Configuration (CPS1/CPS2/Neo-Geo MVS aesthetic)
 */
export const RETRO_ARCADE_VOICE_CONFIG = {
  enabled: true,                 // Master toggle for 90s Arcade Retro Voiceline DSP processing
  highpassFreq: 240,             // Cuts modern sub-bass boom (Hz)
  highpassQ: 0.707,
  peakingFreq: 2200,             // Classic arcade forward vocal bite (Hz)
  peakingGain: 3.8,              // Gain boost (dB)
  peakingQ: 1.2,
  lowpassFreq: 4200,             // 16-bit / 22kHz DAC rolloff (Hz)
  lowpassQ: 0.85,
  saturationDrive: 1.30,         // Warm arcade cabinet soft-clip saturation drive
  speedMultiplier: 1.03,         // Arcade PCB audio clock pace multiplier (+3%)
  enableSlapbackUltimates: true, // Short 85ms slapback echo for domain expansions & massive ultimates
  slapbackDelaySec: 0.085,
  slapbackFeedback: 0.18,
  slapbackMix: 0.22,
};
