export const AUDIO_CONFIG = {
  // UI & General
  'ui_click': 'Assets/Sound Effects/Skills/dash1.mp3',
  'ui_hover': 'Assets/Sound Effects/Skills/dash3.mp3',

  // Attacks
  'attack_explosion': 'Assets/Sound Effects/Attacks/explosion.mp3',
  'attack_fireball': 'Assets/Sound Effects/Skills/fugatravel.mp3',
  'attack_fleshhit': 'Assets/Sound Effects/Attacks/fleshhit.mp3',
  'attack_groundsmash': 'Assets/Sound Effects/Attacks/groundSmash.mp3',
  'attack_swordswing': 'Assets/Sound Effects/Attacks/swordswing.mp3',
  
  // Effects
  'effect_flare': 'Assets/Sound Effects/SkillEffects/flare.mp3',
  'effect_infinity_collide': 'Assets/Sound Effects/SkillEffects/infinity-collide.mp3',

  // Skills
  'skill_backstab': 'Assets/Sound Effects/Skills/backstab.mp3',
  'skill_comerika': 'Assets/Sound Effects/Skills/comerika.mp3',
  'skill_dash1': 'Assets/Sound Effects/Skills/dash1.mp3',
  'skill_dash3': 'Assets/Sound Effects/Skills/dash3.mp3',
  'skill_dash5': 'Assets/Sound Effects/Skills/dash5.mp3',
  'skill_domainexpansion': 'Assets/Sound Effects/Skills/domainexpansion.mp3',
  'skill_enhance': 'Assets/Sound Effects/Skills/enhance.mp3',
  'skill_fuga': 'Assets/Sound Effects/Skills/fuga.mp3',
  'skill_gojodomain': 'Assets/Sound Effects/Skills/gojodomain.mp3',
  'skill_machinebroken': 'Assets/Sound Effects/Skills/machinebroken.mp3',
  'skill_mixing': 'Assets/Sound Effects/Skills/mixing.mp3',
  'skill_parry': 'Assets/Sound Effects/Skills/parry.mp3',
  'skill_redcharging': 'Assets/Sound Effects/Skills/redcharging.mp3',
  'skill_rikaAppearance1': 'Assets/Sound Effects/Skills/rikaAppearance1.mp3',
  'skill_shieldcharge': 'Assets/Sound Effects/Skills/shieldcharge.mp3',
  'skill_spinslash': 'Assets/Sound Effects/Skills/spinslash.mp3',
  'skill_thunderstrike': 'Assets/Sound Effects/Skills/thunderstrike.mp3',
  'skill_todoclap': 'Assets/Sound Effects/Skills/todo-clap.mp3',
  'skill_genosinceneratevoice': 'Assets/Sound Effects/Skills/genos-incenerate-voice.mp3',
  'skill_genosinceneratecharging': 'Assets/Sound Effects/Skills/genos-incenerate-charging.mp3',
  'skill_genosincenerateblast': 'Assets/Sound Effects/Skills/genos-incenerate-blast.mp3',
  'skill_genosultimatecharging': 'Assets/Sound Effects/Skills/genos-ultimatecharging.mp3',
  'skill_genosultimateblast': 'Assets/Sound Effects/Skills/genos-ultimateblast.mp3',
  'skill_genosmachinegunblowvoice': 'Assets/Sound Effects/Skills/genos-machinegunblow-voice.mp3',
  'skill_genosrecovery': 'Assets/Sound Effects/Skills/genos-recovery.mp3',
  'skill_genosrangeattack': 'Assets/Sound Effects/Attacks/genos-range-attack.mp3',
  'skill_genosdashnoise': 'Assets/Sound Effects/Skills/genos-dash-noise.mp3',
  'skill_todotadakachannelvoice': 'Assets/Sound Effects/Skills/todo-tadakaimagination-voiceline.mp3',
  'skill_todotadakabgsong': 'Assets/Sound Effects/Skills/todo-tadaka-background-song.mp3',
  'skill_todomybestfriend': 'Assets/Sound Effects/SkillEffects/todo-voiceline-mybestfriend.mp3',
  'skill_yujibestfriend': 'Assets/Sound Effects/SkillEffects/yuji-voiceline-bestfriend.mp3',
  'skill_saitamachampion': 'Assets/Sound Effects/SkillEffects/saitama-champion-voiceline.mp3',
  'skill_johnwick_shell_drop': 'Assets/Sound Effects/Skills/johnwick-bulleshell-drop.mp3',
  'skill_johnwick_gun_drop': 'Assets/Sound Effects/Skills/johnwick-gundrop.mp3',
  'skill_johnwick_gun_switch': 'Assets/Sound Effects/Skills/johnwick-gunswitch.mp3',
  'skill_johnwick_m4_reload': 'Assets/Sound Effects/Skills/johnwick-m4-reload.mp3',
  'skill_johnwick_m4_shot': 'Assets/Sound Effects/Skills/johnwick-m4-shot.mp3',
  'skill_johnwick_pencil_stab': 'Assets/Sound Effects/Skills/johnwick-pencilstab.mp3',
  'skill_johnwick_pistol_reload': 'Assets/Sound Effects/Skills/johnwick-pistol-reload.mp3',
  'skill_johnwick_pistol_shot': 'Assets/Sound Effects/Skills/johnwick-pistol-shot.mp3',
  'skill_johnwick_shotgun_crack': 'Assets/Sound Effects/Skills/johnwick-shotgun-crack.mp3',
  'skill_johnwick_shotgun_reload': 'Assets/Sound Effects/Skills/johnwick-shotgun-reload.mp3',
  'skill_johnwick_switchgun_voice': 'Assets/Sound Effects/Skills/johnwick-switchgun-voiceline.mp3',
  'skill_johnwick_rollback_voice': 'Assets/Sound Effects/Skills/Johnwick-rollback-voiceline.mp3',
  'skill_engineer_sentry_destroyed': 'Assets/Sound Effects/Skills/engineer-sentrydestroyed.mp3',
  'skill_engineer_sentry_detected': 'Assets/Sound Effects/Skills/engineer-sentrydetected.mp3',
  'skill_engineer_sentry_gunshot': 'Assets/Sound Effects/Skills/engineer-sentrygunshot.mp3',
  'skill_engineer_sentry_reloaded': 'Assets/Sound Effects/Skills/engineer-sentryreloaded.mp3',
  'skill_engineer_sentry_reloading': 'Assets/Sound Effects/Skills/engineer-sentryreloading.mp3',

  // CJ Grove Street
  'skill_cj_carroam_noise': 'Assets/Sound Effects/Skills/cj-carroam-noise.mp3',
  'skill_cj_cheatactivated_banner': 'Assets/Sound Effects/Skills/cj-cheatactivated-banner.mp3',
  'skill_cj_deathmusic': 'Assets/Sound Effects/Skills/cj-deathmusic.mp3',
  'skill_cj_grovestreet_voiceline': 'Assets/Sound Effects/Skills/cj-GROVESTREET4LIFE-voiceline.mp3',
  'skill_cj_homiesarrival_voiceline': 'Assets/Sound Effects/Skills/cj-homiesarrival-voiceline.mp3',
  'skill_cj_homiearrival_voiceline2': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline2.mp3',
  'skill_cj_homiearrival_voiceline3': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline3.mp3',
  'skill_cj_homiearrival_voiceline4': 'Assets/Sound Effects/Skills/cj-homiearrival-voiceline4.mp3',
  'skill_cj_homies_noise1': 'Assets/Sound Effects/Skills/cj-homies-noise1.mp3',
  'skill_cj_homies_noise2': 'Assets/Sound Effects/Skills/cj-homies-noise2.mp3',
  'skill_cj_homie_noise3': 'Assets/Sound Effects/Skills/cj-homie-noise3.mp3',
  'skill_cj_homie_noise4': 'Assets/Sound Effects/Skills/cj-homie-noise4.mp3',
  'skill_cj_homie_noise5': 'Assets/Sound Effects/Skills/cj-homie-noise5.mp3',
  'skill_cj_intro_voiceline': 'Assets/Sound Effects/Skills/cj-intro-voiceline.mp3',
  'skill_cj_respectoverlay_bgmusic': 'Assets/Sound Effects/Skills/cj-respectoverlay-bgmusic.mp3',
  'skill_cj_typeclick1letter_noise': 'Assets/Sound Effects/Skills/cj-typeclick1letter-noise.mp3'
};
